CREATE TABLE IF NOT EXISTS usuarios (
	USUARIO_ID INT PRIMARY KEY AUTO_INCREMENT,
	NOME_DE_USUARIO VARCHAR(255) NOT NULL,
	SENHA VARCHAR(255) NOT NULL,
	EMAIL VARCHAR(255) NOT NULL,
	NOME_COMPLETO VARCHAR(255),
	USUARIO_PERFIL ENUM('ROLE_USUARIO', 'ROLE_ADMIN'),
	SITUACAO ENUM('ATIVO', 'INATIVO', 'SUSPENSO', 'VERIFICACAO_DO_EMAIL_PENDENTE'),
	DATA_DE_REGISTRO TIMESTAMP NOT NULL,
	ULTIMA_MODIFICACAO TIMESTAMP NOT NULL
);
